### PR TITLE
Handle archives with a single top-level '.' member

### PR DESCRIPTION
**Pull request by jhermann**
See https://files.pythonhosted.org/packages/b3/85/85adc67267c62eb75fa22af2a28f0d26f7add039c266d6406b37d8e13284/feedgen-0.5.0.linux-x86_64.tar.gz for an example

### CODE REVIEW

**Comment by jhermann** [comment]
BTW, the additional `if` in this code would improve the debugging experience (from an "AttributeError on NoneType object" to something more informative):

```py
        if not self._info:
            raise RuntimeError('INTERNAL ERROR: Empty tarinfo for {!r}'.format(path))

        # extract to cache
        self.descriptor.extract(member=self._info, path=str(self.cache_path))
```

**Comment by jhermann** [comment]
Failing checks are due to zipp not managed to version 1.1.0 for Python 3.5, i.e. unrelated to the change.

**Comment by orsinium** [comment]
Great! Thank you. I never thought it is legal. Creating `.` directory is a good way to mess up everything in UNIX :)

**Comment by eli-schwartz** [comment]
That file doesn't even make sense, it's not created by any sort of sdist generator -- it only contains ./usr/lib/python3.5/site-packages/ and is totally invalid in every possible respect.

If you look at https://github.com/lkiesow/python-feedgen/commits/v0.5.1 you'll see the sole purpose of the release 6 minutes later was to rerelease the software with a non-broken sdist upload. Arguably the release should have been deleted entirely from PyPI, since it contains semantically invalid contents that don't parse as an sdist and no one could have pinned such a dependency anyway (the usual rationale for "don't delete releases, it breaks people's CI").

**Comment by orsinium** [comment]
The PEP about yanked releases is accepted and supported by pip. So, there is a way to remove a release without breaking lockfiles.

So, is it better to drop this hack? Is there another example of dot in an archive? And even if so, the PR adds support for dot only as the root directory.

**Comment by eli-schwartz** [comment]
Well, I don't think it should break anything, so the question becomes, do you say "less is more" and delete it, or do you say "it's possible other such files exist which are also valid sdists" and keep the extra code around just in case.

@jhermann I'm curious if you're aware of other examples, which would actually be able to be installed using tools such as pip install?

**Comment by jhermann** [comment]
I just tried to fix what I was confronted with, did not investigate further at the time.

**Pull request merged**
